version: '3.3'

services:

  domainmod:
    image: prudave/domainmod:latest
    container_name: 'software'
    depends_on:
      - 'domainmoddb'
    networks:
      - 'frontend'
      - 'backend'
    ports:
      - '80:80'
      - '443:80'
    restart: 'always'

  domainmoddb:
    image: prudave/domainmoddb:latest
    container_name: 'database'
    environment:
      TZ: 'America/Vancouver'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'no'
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_DATABASE: 'domainmod'
      MYSQL_USER: 'domainmod'
      MYSQL_PASSWORD: 'password'
    networks:
      - 'backend'
    ports:
      - '3306:3306'
    restart: 'always'
    volumes:
      - './database:/var/lib/mysql'

networks:
  backend:
  frontend:
